DELETE http://localhost:3000/api/products/60e24afd384bff31682252c3 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTI0OTFiMmVlOWZiMmViMDUwNTY5OSIsImVtYWlsIjoidGVzdEBleHByZXNzLmNsIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE2MjU0NDI1OTEsImV4cCI6MTYyODAzNDU5MX0.X1EWLxX8aJ826pZbiyjCP_gjyA7yNrKGZmTTWDLOGDM